import type { CleImage } from './images.gen'
import type { Localized } from '@/lib/i18n'

/**
 * Portfolio (brief §6.5, étapes 8-9, enrichi à l'étape 15 bis passe A).
 *
 * Le champ `publiable` gouverne le rendu de la FICHE partout (grille,
 * études de cas, accueil, attribution) : rien ne se montre avec un nom de
 * client sans validation (asset n°7). Les entrées sont préparées — images
 * remplies depuis le portfolio du site actuel — et s'allumeront à la
 * bascule du booléen.
 *
 * RÉGIME DISTINCT — images de PÔLE : une photo de réalisation montre un
 * produit posé dans l'espace public ; elle est montrable en contexte pôle
 * (vignette, ouverture de fiche métier, bande-galerie) dès maintenant,
 * mais SANS le nom du client tant que `publiable` est false. L'image
 * seule, jamais l'attribution. Seules les pages réalisations et toute
 * mention nominative restent sous le régime `publiable`.
 *
 * Clients lus des noms de fichiers du site actuel — jamais déduits.
 * dimensions/annee/resume : null tant que non documentés (asset n°12).
 */
export type Realisation = {
  slug: string
  nom: Localized
  client: string
  /** Slug du pôle métier (content/metiers.ts). */
  pole: string
  /** Étiquettes techniques, affichées en .data. */
  techniques: Localized[]
  /** Nourrissent une <Cote>. null si non connues — jamais inventées. */
  dimensions: { largeurM: number; hauteurM: number } | null
  annee: number | null
  /** 2-3 phrases factuelles. null tant que le projet n'est pas documenté. */
  resume: Localized | null
  /** Clés du manifeste images.gen.ts ; la première est la vignette. */
  images: CleImage[]
  /** Gouverne fiche et attribution : rien ne se publie sans validation. */
  publiable: boolean
}

const t = (fr: string, en: string): Localized => ({ fr, en })

export const realisations: Realisation[] = [
  /* ——— Les trois fiches d'origine (étape 8) ——— */
  {
    slug: 'trophee-semi-marathon-somone',
    nom: t('Trophée du Semi-Marathon de la Somone', 'Somone Half-Marathon trophy'),
    client: 'Semi-Marathon de la Somone',
    pole: 'objets',
    techniques: [
      t('Acrylique découpé laser', 'Laser-cut acrylic'),
      t('Socle bois', 'Wooden base'),
      t('Laiton gravé', 'Engraved brass'),
    ],
    dimensions: null,
    annee: null,
    resume: null,
    /* Photo uploadée par le client (étape 15 bis). */
    images: ['realisations/trophee-semi-marathon-somone'],
    publiable: false,
  },
  {
    slug: 'trophees-maggi',
    nom: t('Trophées Maggi', 'Maggi trophies'),
    client: 'Maggi',
    pole: 'objets',
    techniques: [
      t('Verre gravé or', 'Gold-engraved glass'),
      t('Coffrets', 'Gift boxes'),
      t('Production en série', 'Series production'),
    ],
    dimensions: null,
    annee: null,
    resume: null,
    /* Photo uploadée par le client (étape 15 bis). */
    images: ['realisations/trophees-maggi'],
    publiable: false,
  },
  {
    /* À CONFIRMER : réalisation à documenter avant publication. Les photos
       GRAVURE-MOTIF-SUR-FER-TERROU-BI du portfolio y sont rattachées
       (étape 15 bis). */
    slug: 'enseigne-terrou-bi',
    nom: t('Enseigne Terrou-Bi', 'Terrou-Bi sign'),
    client: 'Terrou-Bi',
    pole: 'signaletique',
    techniques: [
      t('Enseigne extérieure', 'Exterior sign'),
      t('Gravure de motif sur fer', 'Pattern engraving on iron'),
    ],
    dimensions: null,
    annee: null,
    resume: null,
    images: [
      'realisations/gravure-motif-sur-fer-terrou-bi',
      'realisations/gravure-motif-sur-fer-terrou-bi-1',
    ],
    publiable: false,
  },

  /* ——— Branding véhicules (portfolio « branding ») ——— */
  {
    slug: 'camion-casamancaise',
    nom: t('Camions La Casamançaise', 'La Casamançaise trucks'),
    client: 'La Casamançaise',
    pole: 'branding-vehicules',
    techniques: [t('Covering de camion', 'Truck wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/camion-casamancaise', 'realisations/camion-casamancaise1'],
    publiable: false,
  },
  {
    slug: 'camion-adja',
    nom: t('Camion Adja', 'Adja truck'),
    client: 'Adja',
    pole: 'branding-vehicules',
    techniques: [t('Covering de camion', 'Truck wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/camion-adja'],
    publiable: false,
  },
  {
    slug: 'camion-fabrimetal',
    nom: t('Camion Fabrimetal', 'Fabrimetal truck'),
    client: 'Fabrimetal',
    pole: 'branding-vehicules',
    techniques: [t('Covering de camion', 'Truck wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/camion-fabrimetal'],
    publiable: false,
  },
  {
    slug: 'camion-sosenap',
    nom: t('Camion Sosenap', 'Sosenap truck'),
    client: 'Sosenap',
    pole: 'branding-vehicules',
    techniques: [t('Covering de camion', 'Truck wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/camion-sosenap'],
    publiable: false,
  },
  {
    slug: 'camion-numerika',
    nom: t('Camion Numerika', 'Numerika truck'),
    client: 'Numerika',
    pole: 'branding-vehicules',
    techniques: [t('Covering de camion', 'Truck wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/camion-numerika'],
    publiable: false,
  },
  {
    slug: 'pickup-begue',
    nom: t('Pick-up Bégué', 'Bégué pickup'),
    client: 'Bégué',
    pole: 'branding-vehicules',
    techniques: [t('Covering de véhicule', 'Vehicle wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/pickup-begue'],
    publiable: false,
  },
  {
    slug: 'tricycle-fiesta',
    nom: t('Tricycle Fiesta', 'Fiesta cargo tricycle'),
    client: 'Fiesta',
    pole: 'branding-vehicules',
    techniques: [t('Covering de tricycle', 'Tricycle wrap')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/tricycle-fiesta'],
    publiable: false,
  },

  /* ——— Objets et personnalisation (portfolio « display » et « gravure ») ——— */
  {
    slug: 'beach-flag-h2ccm',
    nom: t('Beach flag H2CCM', 'H2CCM beach flag'),
    client: 'H2CCM',
    pole: 'objets',
    techniques: [t('Beach flag', 'Beach flag')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/beach-flag-h2ccm'],
    publiable: false,
  },
  {
    slug: 'roll-up-gga',
    nom: t('Roll-up GGA', 'GGA roll-up'),
    client: 'GGA',
    pole: 'objets',
    techniques: [t('Roll-up', 'Roll-up banner')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/roll-up-gga'],
    publiable: false,
  },
  {
    slug: 'presentoir-sedima',
    nom: t('Présentoir Sedima', 'Sedima display stand'),
    client: 'Sedima',
    pole: 'objets',
    techniques: [t('Présentoir', 'Display stand')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/presentoire-sedima'],
    publiable: false,
  },
  {
    slug: 'trophee-credit-international',
    nom: t('Trophée Crédit International', 'Crédit International trophy'),
    client: 'Crédit International',
    pole: 'objets',
    techniques: [t('Trophée gravé', 'Engraved trophy')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/trophee-credit-international'],
    publiable: false,
  },
  {
    slug: 'decoupe-pvc-sanlam',
    nom: t('Découpe PVC Sanlam', 'Sanlam PVC cutting'),
    client: 'Sanlam',
    pole: 'objets',
    techniques: [t('Découpe PVC', 'PVC cutting')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/decoupe-pvc-sanlam'],
    publiable: false,
  },

  /* ——— Impression numérique (portfolio « impression numérique ») ——— */
  {
    slug: 'bache-lasa',
    nom: t('Bâches Lasa', 'Lasa banners'),
    client: 'Lasa',
    pole: 'impression-numerique',
    techniques: [t('Bâche imprimée', 'Printed banner')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/bache-lassa', 'realisations/lasa', 'realisations/lasa1'],
    publiable: false,
  },
  {
    slug: 'panneau-dmc',
    nom: t('Panneau DMC', 'DMC panel'),
    client: 'DMC',
    pole: 'impression-numerique',
    techniques: [t('Impression sur panneau', 'Panel printing')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/panneau-dmc'],
    publiable: false,
  },

  /* ——— Menuiserie et façade (portfolio « revêtement ») ——— */
  {
    slug: 'facade-crystal',
    nom: t('Façade Crystal', 'Crystal façade'),
    client: 'Crystal',
    pole: 'menuiserie-facade',
    techniques: [t('Habillage de façade', 'Façade cladding')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/facade-crystal'],
    publiable: false,
  },
  {
    slug: 'revetement-facade-sonam',
    nom: t('Revêtement de façade Sonam', 'Sonam façade cladding'),
    client: 'Sonam',
    pole: 'menuiserie-facade',
    techniques: [t('Revêtement de façade', 'Façade cladding')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/revetement-de-facade-sonam'],
    publiable: false,
  },
  {
    slug: 'revetement-lettrage-uba',
    nom: t('Revêtement et lettrage UBA', 'UBA cladding and lettering'),
    client: 'UBA',
    pole: 'menuiserie-facade',
    techniques: [t('Revêtement', 'Cladding'), t('Découpe lettrage', 'Cut lettering')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/revetement-decoupe-lettrage-uba'],
    publiable: false,
  },
  {
    slug: 'facade-lasa',
    nom: t('Façade Lasa', 'Lasa façade'),
    client: 'Lasa',
    pole: 'menuiserie-facade',
    techniques: [t('Habillage de façade', 'Façade cladding')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/facade-lasa'],
    publiable: false,
  },
  {
    slug: 'facade-kia',
    nom: t('Façade Kia', 'Kia façade'),
    client: 'Kia',
    pole: 'menuiserie-facade',
    techniques: [t('Habillage de façade', 'Façade cladding')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/facade-kia'],
    publiable: false,
  },
  {
    /* À CONFIRMER : « galandou » lu du nom de fichier — client ou
       adresse (Galandou Diouf) à préciser avant publication. */
    slug: 'facade-galandou',
    nom: t('Façade Galandou', 'Galandou façade'),
    client: 'Galandou',
    pole: 'menuiserie-facade',
    techniques: [t('Habillage de façade', 'Façade cladding')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/facade-galandou'],
    publiable: false,
  },

  /* ——— Signalétique (portfolio « signalétique externe/interne ») ——— */
  {
    slug: 'enseigne-kosen',
    nom: t('Enseigne Kosen', 'Kosen sign'),
    client: 'Kosen',
    pole: 'signaletique',
    techniques: [t('Enseigne extérieure', 'Exterior sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-kosen', 'realisations/enseigne-kosen1'],
    publiable: false,
  },
  {
    slug: 'enseignes-ecobank',
    nom: t('Enseignes Ecobank', 'Ecobank signs'),
    client: 'Ecobank',
    pole: 'signaletique',
    techniques: [t('Enseigne lumineuse', 'Illuminated sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: [
      'realisations/enseigne-lumineuse-ecobank',
      'realisations/enseigne-ecobank',
      'realisations/enseigne-ecobank1',
    ],
    publiable: false,
  },
  {
    slug: 'enseignes-mitsubishi',
    nom: t('Enseignes Mitsubishi', 'Mitsubishi signs'),
    client: 'Mitsubishi',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-mitsubishi', 'realisations/enseigne-mitsubishi1'],
    publiable: false,
  },
  {
    slug: 'signaletique-gga',
    nom: t('Enseignes et plaques GGA', 'GGA signs and plaques'),
    client: 'GGA',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign'), t('Plaque', 'Plaque'), t('Enseigne drapeau', 'Projecting sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: [
      'realisations/enseigne-gga',
      'realisations/enseigne-drapeau-gga',
      'realisations/plaque-gga',
      'realisations/plaque-gga1',
    ],
    publiable: false,
  },
  {
    slug: 'enseigne-ibis',
    nom: t('Enseigne Ibis', 'Ibis sign'),
    client: 'Ibis',
    pole: 'signaletique',
    techniques: [t('Enseigne extérieure', 'Exterior sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-ibis'],
    publiable: false,
  },
  {
    slug: 'plaques-ibis',
    nom: t('Plaques Ibis', 'Ibis plaques'),
    client: 'Ibis',
    pole: 'signaletique',
    techniques: [t('Plaque', 'Plaque')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/plaque-ibis', 'realisations/plaque-ibis1'],
    publiable: false,
  },
  {
    slug: 'signaletique-bdk',
    nom: t('Enseigne et plaque plexi BDK', 'BDK sign and plexiglass plaque'),
    client: 'BDK',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign'), t('Plaque plexiglas', 'Plexiglass plaque')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-bdk', 'realisations/plaque-plexi-bdk'],
    publiable: false,
  },
  {
    slug: 'enseigne-basilic',
    nom: t('Enseigne Basilic', 'Basilic sign'),
    client: 'Basilic',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-basilic', 'realisations/enseigne-basilic-1'],
    publiable: false,
  },
  {
    slug: 'enseigne-be-sport',
    nom: t('Enseigne Be Sport', 'Be Sport sign'),
    client: 'Be Sport',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-be-sport', 'realisations/enseigne-besport'],
    publiable: false,
  },
  {
    slug: 'enseignes-dmc',
    nom: t('Enseignes DMC', 'DMC signs'),
    client: 'DMC',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-dmc', 'realisations/enseigne-dmc-1'],
    publiable: false,
  },
  {
    slug: 'enseignes-uba',
    nom: t('Enseignes UBA', 'UBA signs'),
    client: 'UBA',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign'), t('Enseigne drapeau', 'Projecting sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-uba', 'realisations/enseigne-drapeau-uba'],
    publiable: false,
  },
  {
    slug: 'signaletique-sahm',
    nom: t('Enseigne et totem SAHM', 'SAHM sign and totem'),
    client: 'SAHM',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign'), t('Totem', 'Totem')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-sahm', 'realisations/totem-sahm'],
    publiable: false,
  },
  {
    slug: 'panneau-jado',
    nom: t('Panneaux Jado', 'Jado panels'),
    client: 'Jado',
    pole: 'signaletique',
    techniques: [t('Panneau', 'Panel')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/panneau-jado', 'realisations/panneau-jado1'],
    publiable: false,
  },
  {
    slug: 'neon-madrague',
    nom: t('Néon La Madrague', 'La Madrague neon'),
    client: 'La Madrague',
    pole: 'signaletique',
    techniques: [t('Néon', 'Neon')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/neon-madrague'],
    publiable: false,
  },
  {
    slug: 'enseigne-drapeau-crystal',
    nom: t('Enseigne drapeau Crystal', 'Crystal projecting sign'),
    client: 'Crystal',
    pole: 'signaletique',
    techniques: [t('Enseigne drapeau', 'Projecting sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-drapeau-crystal'],
    publiable: false,
  },
  {
    slug: 'totem-lasa',
    nom: t('Totem Lasa', 'Lasa totem'),
    client: 'Lasa',
    pole: 'signaletique',
    techniques: [t('Totem', 'Totem')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/totem-lasa'],
    publiable: false,
  },
  {
    slug: 'enseigne-lasa',
    nom: t('Enseigne Lasa', 'Lasa sign'),
    client: 'Lasa',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-lasa'],
    publiable: false,
  },
  {
    slug: 'totem-cta',
    nom: t('Totem CTA', 'CTA totem'),
    client: 'CTA',
    pole: 'signaletique',
    techniques: [t('Totem', 'Totem')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/totem-cta'],
    publiable: false,
  },
  {
    slug: 'enseigne-ccs',
    nom: t('Enseigne CCS', 'CCS sign'),
    client: 'CCS',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-ccs'],
    publiable: false,
  },
  {
    slug: 'enseigne-universal-industries',
    nom: t('Enseigne Universal Industries', 'Universal Industries sign'),
    client: 'Universal Industries',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-universal-industries'],
    publiable: false,
  },
  {
    slug: 'enseigne-super-u',
    nom: t('Enseigne Super U', 'Super U sign'),
    client: 'Super U',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-super-u'],
    publiable: false,
  },
  {
    slug: 'enseigne-sonam',
    nom: t('Enseigne Sonam', 'Sonam sign'),
    client: 'Sonam',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-sonam'],
    publiable: false,
  },
  {
    slug: 'decoupe-pvc-sonam',
    nom: t('Découpe PVC Sonam', 'Sonam PVC cutting'),
    client: 'Sonam',
    pole: 'signaletique',
    techniques: [t('Découpe PVC', 'PVC cutting')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/decoupe-pvc-sonam'],
    publiable: false,
  },
  {
    slug: 'enseigne-kaik',
    nom: t('Enseigne Kaik', 'Kaik sign'),
    client: 'Kaik',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-kaik'],
    publiable: false,
  },
  {
    slug: 'enseigne-dongfeng',
    nom: t('Enseigne Dongfeng', 'Dongfeng sign'),
    client: 'Dongfeng',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-dongfeng'],
    publiable: false,
  },
  {
    slug: 'enseigne-foundever',
    nom: t('Enseigne Foundever', 'Foundever sign'),
    client: 'Foundever',
    pole: 'signaletique',
    techniques: [t('Enseigne', 'Sign')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/enseigne-foundever'],
    publiable: false,
  },
  {
    slug: 'signaletique-rfi',
    nom: t('Signalétique RFI', 'RFI signage'),
    client: 'RFI',
    pole: 'signaletique',
    techniques: [t('Signalétique intérieure', 'Interior signage')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/rfi'],
    publiable: false,
  },
  {
    slug: 'tableau-basma',
    nom: t('Tableau Basma', 'Basma board'),
    client: 'Basma',
    pole: 'signaletique',
    techniques: [t('Tableau', 'Board')],
    dimensions: null,
    annee: null,
    resume: null,
    images: ['realisations/tableau-basma'],
    publiable: false,
  },
]

/** Libellés des pages réalisations. */
export const realisationsTextes = {
  page: {
    titre: { fr: 'Réalisations', en: 'Work' },
    description: {
      fr: 'Réalisations de l’atelier Numerika à Dakar : impression, signalétique, objets, textile.',
      en: 'Work from the Numerika workshop in Dakar: printing, signage, objects, textile.',
    },
    filtreTous: { fr: 'Tous les pôles', en: 'All units' },
  },
  vide: {
    message: {
      fr: 'Réalisations en cours de documentation.',
      en: 'Work being documented.',
    },
    whatsapp: {
      fr: 'Bonjour, je souhaite voir des réalisations de Numerika.',
      en: 'Hello, I would like to see examples of Numerika’s work.',
    },
  },
  fiche: {
    contexte: { fr: 'Le contexte', en: 'The context' },
    reponse: { fr: 'La réponse', en: 'The response' },
    client: { fr: 'Client', en: 'Client' },
    annee: { fr: 'Année', en: 'Year' },
    techniques: { fr: 'Techniques', en: 'Techniques' },
    dimensions: { fr: 'Dimensions', en: 'Dimensions' },
  },
} as const
